project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - "notes/*.md"
    - experiments/classifier/chap1-no_hidden_layer-MSE_loss.ipynb

# Multiple sidebars / navbar: https://quarto.org/docs/websites/website-navigation.html
website:
  title: "NNs and DL"
  repo-url: https://github.com/Guppy16/NNs-and-Deep-Learning
  sidebar:
    style: docked
    contents:
      - text: Introduction
        href: index.qmd
      - text: VAE
        href: notes/VAE.md
      - section: Notes
        contents:
          - text: Intro to Neural Networks
            href: notes/1-NNs_Intro.md
          - text: Backpropagation
            href: notes/2-Backpropagation.md
          - text: Improving Learning
            href: notes/3-Improving_Learning.md
      - text: Python for NNs
        href: notes/composition.md

  navbar:
    background: primary
    search: true
    # menu:
    #   - href: README.md
    tools:
      - icon: twitter-x
        href: https://x.com/AkashGu30808281
      - icon: github
        href: https://github.com/Guppy16/NNs-and-Deep-Learning



format:
  html:
    theme:
      dark: darkly
      light: flatly
    # css: styles.css
    theme-dark: true
    toc: true